exports.LOGIN_SCHIDPW = "MENU00001";			// 아이디 비밀번호 찾기
exports.DASHBOARD = "MENU001";					// 데쉬보드
exports.MODEL_MANAGER = "MENU00201";			// 모델 관리
exports.SERVICE_MANAGER = "MENU00301";			// Service관리
exports.ADMIN_HIST_SERVICEEXEC = "MENU00303";	// Service 실행결과 이력
exports.ADMIN_USERMGR = "MENU00401";			// 사용자 관리
exports.ADMIN_HIST_LOGIN = "MENU0040505";		// 사용자 로그인 이력
exports.ADMIN_HIST_MODELREG = "MENU0040501";	// Model등록 이력
exports.ADMIN_HIST_SCALEINOUT = "MENU0040504";	// Resource 이력
exports.ADMIN_SACLEINOUTMGR = "MENU00403";		// Sale In Out 관리
exports.ADMIN_SERVICEGROUP = "MENU00407";		// 서비스 그룹
exports.ADMIN_COMMONCODE = "MENU00406";			// 공통코드