DELIMITER &&
CREATE FUNCTION FN_GET_USER_NAME(
    P_USER_ID VARCHAR(20)
)
RETURNS VARCHAR(10)
BEGIN
    DECLARE RET VARCHAR(10);
    
    SELECT USER_NAME INTO RET FROM USER
        WHERE USER_ID=P_USER_ID;
    RETURN RET;
END &&
DELIMITER ;
